name: levpay

services:
  gateway:
    restart: unless-stopped
    image: nginx:alpine
    container_name: levpay_gateway
    profiles: ["full", "semi-local", "gateway", "minimal"]
    ports:
      - 4003:80
    environment:
      APP_SERVICE_URL: levpay_app:5000
      AUTH_SERVICE_URL: levpay_auth:5000
      USER_SERVICE_URL: levpay_user:5000
      WALLET_SERVICE_URL: levpay_wallet:5000
      TRANSACTION_SERVICE_URL: levpay_transaction:5000
      KYC_SERVICE_URL: levpay_kyc:5000
      FILE_SERVICE_URL: levpay_file:5000
      NOTIFICATION_SERVICE_URL: levpay_notification:5000
      BILLING_SERVICE_URL: levpay_billing:5000
      ADMIN_SERVICE_URL: levpay_admin:5000
      CRON_SERVICE_URL: levpay_cron:5000
      MINIO_SERVICE_URL: levpay_minio:9001
      RMQ_SERVICE_URL: levpay_rabbitmq:15672
    volumes:
      - ./nginx/templates/api-local.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
    depends_on:
      - redis
      - db
      - rabbitmq
      - minio
      - app
      - auth
      - user
      - wallet
      - transaction
      - kyc
      - file
      - notification
      - billing
      - admin
      - cron
    command: >
      sh -c 'until wget -qO- http://levpay_app:5000/health >/dev/null 2>&1; do echo "waiting for app..."; sleep 1; done;
             echo "App service ready, starting nginx...";
             /docker-entrypoint.sh nginx -g "daemon off;"'
    networks:
      - levpay_network

  redis:
    image: redis:alpine
    container_name: levpay_redis
    restart: always
    profiles: ["full", "backend", "minimal"]
    volumes:
      - levpay_redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASS:-redispassword}
    command:
      - redis-server
      - --appendonly yes
      - --maxmemory 128mb
      - --maxmemory-policy allkeys-lru
      - --dir /data
    ports:
      - 6383:6379
    networks:
      - levpay_network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: levpay_rabbitmq
    container_name: levpay_rabbitmq
    restart: always
    profiles: ["full", "backend", "minimal"]
    environment:
      - RABBITMQ_DEFAULT_USER=rmquser
      - RABBITMQ_DEFAULT_PASS=rmqpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,info},{default,info}] disk_free_limit 1073741824
    volumes:
      - levpay_rmq_data:/var/lib/rabbitmq
    ports:
      - "5675:5672"
      - "15675:15672"
    networks:
      - levpay_network

  db:
    image: postgres:16-alpine
    container_name: levpay_db
    restart: unless-stopped
    profiles: ["full", "backend", "minimal"]
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-levpay}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - levpay_pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5437:5432
    networks:
      - levpay_network
    command: >
      postgres
      -c shared_buffers=128MB
      -c max_connections=50
      -c effective_cache_size=256MB

  minio:
    image: minio/minio
    container_name: levpay_minio
    profiles: ["full", "storage", "minimal"]
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS:-minioadmin}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL:-https://127.0.0.1:4003/minio/ui/}
    command: server /data --console-address ":9001"
    volumes:
      - levpay_minio_data:/data
    ports:
      - "9004:9000"
      - "9005:9001"
    networks:
      - levpay_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=app_prod
    container_name: levpay_app
    restart: unless-stopped
    profiles: ["full", "semi-local", "app", "minimal"]
    env_file: .env
    environment:
      APP_SERVICE: app
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
      - minio
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5001:5000"
    networks:
      - levpay_network

  auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=auth_prod
    container_name: levpay_auth
    restart: unless-stopped
    profiles: ["full", "semi-local", "auth", "minimal"]
    env_file: .env
    environment:
      APP_SERVICE: auth
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5002:5000"
    networks:
      - levpay_network

  user:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=user_prod
    container_name: levpay_user
    restart: unless-stopped
    profiles: ["full", "semi-local", "user", "minimal"]
    env_file: .env
    environment:
      APP_SERVICE: user
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5003:5000"
    networks:
      - levpay_network

  wallet:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=wallet_prod
    container_name: levpay_wallet
    restart: unless-stopped
    profiles: ["full", "semi-local", "wallet", "minimal"]
    env_file: .env
    environment:
      APP_SERVICE: wallet
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5004:5000"
    networks:
      - levpay_network

  transaction:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=transaction_prod
    container_name: levpay_transaction
    restart: unless-stopped
    profiles: ["full", "semi-local", "transaction", "minimal"]
    env_file: .env
    environment:
      APP_SERVICE: transaction
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5005:5000"
    networks:
      - levpay_network

  kyc:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=kyc_prod
    container_name: levpay_kyc
    restart: unless-stopped
    profiles: ["full", "semi-local", "kyc", "minimal"]
    env_file: .env
    environment:
      APP_SERVICE: kyc
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
      - minio
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5006:5000"
    networks:
      - levpay_network

  file:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=file_prod
    container_name: levpay_file
    restart: unless-stopped
    profiles: ["full", "semi-local", "file", "minimal"]
    env_file: .env
    environment:
      APP_SERVICE: file
      DB_HOST: levpay_db
      MINIO_HOST: levpay_minio
    depends_on:
      - db
      - rabbitmq
      - redis
      - minio
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5007:5000"
    networks:
      - levpay_network

  notification:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=notification_prod
    container_name: levpay_notification
    restart: unless-stopped
    profiles: ["full", "semi-local", "notification", "minimal"]
    env_file: .env
    environment:
      APP_SERVICE: notification
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5008:5000"
    networks:
      - levpay_network

  billing:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=billing_prod
    container_name: levpay_billing
    restart: unless-stopped
    profiles: ["full", "semi-local", "billing", "minimal"]
    env_file: .env
    environment:
      APP_SERVICE: billing
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5009:5000"
    networks:
      - levpay_network

  admin:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=admin_prod
    container_name: levpay_admin
    restart: unless-stopped
    profiles: ["full", "semi-local", "admin"]
    env_file: .env
    environment:
      APP_SERVICE: admin
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5010:5000"
    networks:
      - levpay_network

  cron:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - MAKE_RULE=cron_prod
    container_name: levpay_cron
    restart: unless-stopped
    profiles: ["full", "semi-local", "cron"]
    env_file: .env
    environment:
      APP_SERVICE: cron
      DB_HOST: levpay_db
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "5011:5000"
    networks:
      - levpay_network

volumes:
  levpay_pg_data:
  levpay_rmq_data:
  levpay_minio_data:
  levpay_redis_data:
  go_mod_cache:

networks:
  levpay_network: